### ISSUE TITLE
Filter / text search on text fields 

### ISSUE THREAD

**Issue by alex-wilmer** [overture-stack/arranger#113]
https://kidsfirst.atlassian.net/wiki/spaces/KFDRC/pages/247005357/File+Table#FileTable-1.2TableRequirements:

point #3 there

- create new OP in sqon

```
{
    op: 'filter',
    content: {
        fields: ['gender', 'age'],
        value: 'hat'
    }
}
```

handle new OP in middleware/filters, transform into list of OR queries 

- wildcard / partial search

**Comment by shanewilson** [comment]
gdcapi has a query param that does this

does a fuzzy search on any fields in the query

```
hits(query: "hat") {
 node {
  gender
  age
 }
}
```

i don't remember the details
