### ISSUE TITLE
🐛 Nested aggregations are coming back as null for some fields

### ISSUE THREAD

**Issue by hlminh2000** [overture-stack/arranger#144]
<img width="715" alt="screen shot 2018-02-14 at 4 27 29 pm" src="https://user-images.githubusercontent.com/11821106/36229139-4bcff126-11a4-11e8-9e9f-9bcc2ebda443.png">
<img width="715" alt="screen shot 2018-02-14 at 4 27 42 pm" src="https://user-images.githubusercontent.com/11821106/36229132-480b1818-11a4-11e8-8ddc-1944072ed994.png">

**Comment by alex-wilmer** [comment]
nice find 👍

**Comment by hlminh2000** [comment]
In `build_aggregations`, the loop over `fields` is overriding the the entire collection of the nested fields on every iteration, resulting in the output `agg` being incorrect. This explains why only the last field of those that share common paths are resolved. This is likely because of the use of `Object.assign` which doesn't do a deep merge. There may be a difference in behaviour between python's library `update` method and the JS `Object.assign`, or there was some error in porting.

Particularly worth noting is that the call to `ensure_path_to_agg` is overriding `agg`. From comparing the code, this seems consistent with the original python code, but could use confirmation.

Some difference in the ported implementation of `build_aggregations` was identified and corrected, but yielded no difference to the result so far.
