### ISSUE TITLE
Table Bugs

### ISSUE THREAD

**Issue by rosibaj** [overture-stack/arranger#167]
- [x] When only 2 files are selected, the table shows empty rows below the 2 items.  When only 2 items are returned, the able should only have 2 rows
- [x] regardless of the number of items, the pagination bar shows 10 pages.  This should show the accurate amount of pages 
~- [ ] Provide multi-Column sort to the left of the columns button~
- [x] Rename "show columns" to Columns
- [x] Add download icon to "Export TSV" text
- [x] When I click on page the last pagination number (10 on the first page), it navigates to page 10 correctly.  However, if I then want to go to page 15 next, I have to click next 5 times.  Instead, next should show the next 10 items so i can click any of the next 10 page numbers.

**Comment by Jephuff** [comment]
@rosibaj for the last point, I made it so the current page is in the centre. Does that work? 

Could `Provide multi-Column sort to the left of the columns button` also be split into it's own ticket?

**Comment by rosibaj** [comment]
@Jephuff Column sort is split into ticket https://github.com/overture-stack/arranger/issues/178

**Comment by Jephuff** [comment]
great! thanks Rosi :)
