### ISSUE TITLE
Exclude date fields from facets in the data portal

### ISSUE THREAD

**Issue by phuongmy** [overture-stack/arranger#221]
For the demo, please exclude the date fields from the facet panel (default and advanced filters).

Note: There is a ticket to provide date picker facet (https://github.com/overture-stack/arranger/issues/186) that we will implement after March 13 demo.

**Comment by alex-wilmer** [comment]
https://github.com/overture-stack/arranger/commit/56cc2d224df3c938cdc8780667b41fa1ce72c15f
