### ISSUE TITLE
Incorrect aggregations in table summary

### ISSUE THREAD

**Issue by andricDu** [overture-stack/arranger#232]
On the surface it looks like a bug related to not doing correct nested aggregations.

![image](https://user-images.githubusercontent.com/6350043/37158971-acd450c6-22ba-11e8-804a-15621cb5b279.png)

It should be impossible to have files without participants.

**Comment by andricDu** [comment]
The current aggregation being returned by the middleware looks like the following:
```json
{
  "query": {
    "match_all": {}
  },
  "aggs": {
    "family.family_id": {
      "terms": {
        "field": "family.family_id",
        "size": 100
      }
    }
  }
}
```

It is missing the nested aggregation.
The correct aggregation looks like:
```json
  "aggs":{
    "participants": {
      "nested": {
        "path": "participants"
      },
      "aggs": {
        "participants.family.family_id": {
          "terms": {
            "field": "participants.family.family_id",
            "size": 100
          }
        }
      }
    }
  }
```

**Comment by andricDu** [comment]
Relevant portion from the mapping:
```json
"file_centric": {
  "properties": {
    "participants": {
            "type": "nested"
    }
  }
}
```

**Comment by Jephuff** [comment]
It should be going to the participant index, so I believe this is the correct aggregation. 
We aren't probably handling the cross index filtering. 

If adding the cross filtering will take us to long, this could be switched to use the file index instead

**Comment by andricDu** [comment]
@Jephuff in that case is the count even correct? 3,711 participants, but only 100 families.

**Comment by alex-wilmer** [comment]
i don't think it *should* be going to the participant index right? it's just a nested agg

**Comment by Jephuff** [comment]
I can update to file index. 
Should we leave this issue to be for the cross index filtering or create a new one?

**Comment by alex-wilmer** [comment]
cross index filtering is one of the first issues!

https://github.com/overture-stack/arranger/issues/19 blocked by sets.

i'm still a little confused what this has to do with cross index though.

**Comment by Jephuff** [comment]
because I was going to the participant index. I'll update these to go to the file index.

**Comment by alex-wilmer** [comment]
ohhhhhh i see you were passing file sqon to participant index

**Comment by andricDu** [comment]
Discussion: https://github.com/kids-first/kf-portal-ui/pull/129
Culprit: https://github.com/overture-stack/arranger/blob/master/modules/middleware/src/aggregations.js#L16

**Comment by phuongmy** [comment]
Seems to work well.
Except I tried File format is fq and I get 0 families although 102 participants.
<img width="1437" alt="screen shot 2018-03-09 at 1 33 01 pm" src="https://user-images.githubusercontent.com/8812383/37223619-1afa8806-239f-11e8-8778-64c596c5e685.png">
