### ISSUE TITLE
Provide the ability to update the display name in facet and file table

### ISSUE THREAD

**Issue by phuongmy** [overture-stack/arranger#243]
Currently if I updated the display name in http://beta.portal.kids-first.io/admin/mar7/file_centric - FIELDS tab then I go to the data portal >> the display name is not updated in the facets and file table.

Please provide a way to update the display name on the UI. We need this for the March 13 demo.
If not possible, I can provide the list of names that we want to display in the file table and default facets.

**Comment by Jephuff** [comment]
This should work right now, but it currently requires you to press the "ARRANGE!" button to show the changes on the portal
unless I misunderstand the ticket :) 

![image](https://user-images.githubusercontent.com/3953093/37182013-612c3498-22fd-11e8-96d7-c5411fc0e368.png)

**Comment by phuongmy** [comment]
Awesome, it worked! I'm closing the issue.
