### ISSUE TITLE
Incorrect use of global aggs.

### ISSUE THREAD

**Issue by andricDu** [overture-stack/arranger#256]
Global aggs are currently breaking the facet/aggs counts in the kf portal. 

It may be related to aggs on sub documents that are two levels deep in nesting.

**Comment by andricDu** [comment]
https://github.com/kids-first/kf-portal-ui/issues/165

**Comment by andricDu** [comment]
Global aggregations are being generated on a nested document to avoid filtering itself, but this is then excluding the nested children of said nested documents from being properly updated.

**Comment by phuongmy** [comment]
https://github.com/overture-stack/arranger/issues/271
