### ISSUE TITLE
Add additional aggregation facet format ( text search)

### ISSUE THREAD

**Issue by rosibaj** [overture-stack/arranger#283]
There is a need for a "text search" style facet that allows users to type in a value in a type-ahead box to select from a large list of fact values.  The best example of this is searching for gene or variant ( examples form ICGC and GDC)

![screen shot 2018-03-15 at 5 25 35 pm](https://user-images.githubusercontent.com/15824252/37491975-e6675a5c-2875-11e8-9192-6e770d310a7e.png)
![screen shot 2018-03-15 at 5 25 23 pm](https://user-images.githubusercontent.com/15824252/37491976-e6770baa-2875-11e8-92a2-982ae41739e1.png)
![screen shot 2018-03-15 at 5 26 12 pm](https://user-images.githubusercontent.com/15824252/37491999-fb4c2268-2875-11e8-9776-e27185a97eb1.png)

**Comment by alex-wilmer** [comment]
The text search leads to choosing a single document right? This is closer to something like a quicksearch / id search since the end result isn't so much an aggregation as it is finding a single item.

Can we merge this idea with the "id" search (which really is an "configurable set of fields" search?

**Comment by phuongmy** [comment]
@alex-wilmer: the text search could apply to fields like Anatomical Site or Diagnosis, so not an id search. 
<img width="330" alt="screen shot 2018-03-19 at 6 08 46 am" src="https://user-images.githubusercontent.com/8812383/37589707-7682ed4a-2b3c-11e8-920e-dce8c248c331.png">

Maybe we need something similar to GDC with a search box on top of the list facet (ability to do keyword match)
<img width="839" alt="screen shot 2018-03-19 at 6 22 16 am" src="https://user-images.githubusercontent.com/8812383/37590224-fdc45c2a-2b3d-11e8-96fa-413b8a103a44.png">

**Comment by rosibaj** [comment]
@alex-wilmer There is still a need to separate some terms (UI transformation and UX wise) even though technically they are leading to the same idea.  For example, in ICGC you can search via autocomplete text boxes of GO terms or Pathways.  While this is technically the same solution, for the user these are different things and lead to a much different interaction.  Also, we could have the need to visually separate out some elements to make it clear to users that it is available.  

Specifically in KF, the HPO searching will require UI/UX manipulation specific to this field.  FOr HPO term searching in KF:

- Users can type in 1) an actual HPO id 2) the HPO corresponding text term or 3) synonyms for the text term. 
- Whatever user select, in the query area, we will show the official HPO text term. 

![screen shot 2018-03-19 at 9 15 50 am](https://user-images.githubusercontent.com/15824252/37597557-226ca5b0-2b56-11e8-8301-841aeda8c256.png)


![screen shot 2018-03-19 at 9 13 54 am](https://user-images.githubusercontent.com/15824252/37597466-eab6536e-2b55-11e8-8158-c83c471a0792.png)

**Comment by phuongmy** [comment]
Done.
