### ISSUE TITLE
Include a `_missing` bucket for all aggregations

### ISSUE THREAD

**Issue by Jephuff** [overture-stack/arranger#288]
- [ ] include a _missing bucket in aggregations
- [ ] provide ability to rename the value `_missing`
- [ ] extend sqon filter to add the right query in es

**Comment by phuongmy** [comment]
Just checking that this ticket will fix the bug where currently if the user selects existing "_missing" value for any facet, it will return 0 file? e.g. with ethnicity is missing

<img width="1414" alt="screen shot 2018-04-06 at 7 48 18 am" src="https://user-images.githubusercontent.com/8812383/38419609-23a61110-396f-11e8-8b76-5352b5b792b0.png">
