### ISSUE TITLE
Add a way to hide aggregations (facet)

### ISSUE THREAD

**Issue by phuongmy** [overture-stack/arranger#306]
Related to https://github.com/overture-stack/arranger/issues/305

`file_size` was set to a type of ID as a way to hide it from aggregations. 

Jeffrey's suggestion is to do something like the table columns having a `show` check for default columns and `active` for all columns --> anything without the active check wouldn't show up.

Any facet filters in Aggregations without the active check would not be displayed in the "All Filters" pop-up (also default facet panel).

**Comment by hlminh2000** [comment]
Jeff's commit includes some stuff that changes the AFV's so I'll look at merging this in after the AFV rewrite is complete
