### ISSUE TITLE
Add support for Manifest IDs / Sets

### ISSUE THREAD

**Issue by andricDu** [overture-stack/arranger#314]
Terms Lookup indexes seem to be appropriate for this.

https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-terms-query.html

**Comment by jgnieuwhof** [comment]
set saving has been added in https://github.com/overture-stack/arranger/pull/325
set sqon parsing has been added in https://github.com/overture-stack/arranger/pull/326

closing this off for now
