### ISSUE TITLE
Allow arranger to receive a custom data fetcher to handle application specific logics

### ISSUE THREAD

**Issue by hlminh2000** [overture-stack/arranger#323]
A lot of arranger components are doing their own data fetching using the built in fetcher. We should add the ability for consuming applications to provide their own data fetcher to arranger. Once that's done, kids-first should be modified to provide its own fetcher that handles the ego token so header logics can be removed from Arranger

**Comment by caravinci** [comment]
closing this ticket as the functionality will be enabled by changes in #730.
