### ISSUE TITLE
0.4.0 Umbrella 

### ISSUE THREAD

**Issue by alex-wilmer** [overture-stack/arranger#341]
With what feels like a pretty successful initial pass via Kids First and HCMI, I think it's time to start formalizing the next release so that codebases using Arranger can prepare for breaking changes.

Here are some major things on my list, in no particular order:

- Option to use a separate DB for Arranger data (instead of using same one as domain data, ie files)
- Move the "project" rest endpoints over to graphql
- Refactor into a core + plugin architecture
- Formalize theming & testing
- Config loading / saving / duplicating
- Scaffolding tools (create-arranger-app, create-arranger-plugin)

- Branding / Visual Identity
- Documentation Site + live examples
- Glossary: Improve / formalize terminology (ie "project" needs a better, more accurate name)
- Dashboard UI / UX redesign

If there's anything you feel should or shouldn't belong in the next release please discuss it here.

Thanks & fantastic work everyone!

**Comment by alex-wilmer** [comment]
Beta Checklist

- [ ] thing

**Comment by rosibaj** [comment]
@hlminh2000 is this ticket still needed?
