### ISSUE TITLE
Improve performance of All Filters

### ISSUE THREAD

**Issue by Fgerthoffert** [overture-stack/arranger#427]
Currently the date aggregations coming from the server is in buckets, which is a very large dataset that takes time to transfer over the wire, and also requires client-side reduction that is slowing down the AFV load time. Rewriting this to use a range aggregation will significantly improve the performance. Todo:

- [x] Arranger back-end support for date agg type
- [x] Arranger front-end support for new date agg type

**Comment by hlminh2000** [comment]
Currently the date aggregations coming from the server is in buckets, which is a very large dataset that takes time to transfer over the wire, and also requires client-side reduction that is slowing down the AFV load time.
Rewriting this to use a range aggregation will significantly improve the performance.

**Comment by rosibaj** [comment]
@hlminh2000 This is working much faster and everything looks good query wise.  I think this is good to merge from my POV!
