### ISSUE TITLE
Update default Slider Facet UX

### ISSUE THREAD

**Issue by rosibaj** [overture-stack/arranger#431]
We want to update the default facet slider UX for arranger.  The new slider should look like this:

![slider-themeshcmi slider](https://user-images.githubusercontent.com/18424138/42392763-e6badf38-8121-11e8-8d78-041da3c20f59.jpg)

![slider-themeskidsfirst slider](https://user-images.githubusercontent.com/18424138/42392764-e6cf1980-8121-11e8-9606-d73ad4ffe4c5.jpg)

Zeplin for HCMI theme: https://zpl.io/2ymZEdo

Zeplin for Kids First theme: https://zpl.io/a3qBDyY

**Comment by kcullion** [comment]
@rosibaj I"m closing as we aren't doing this version for the slider anymore
