### ISSUE TITLE
⚡️ Cardinality field in the gql buckets arregations

### ISSUE THREAD

**Issue by hlminh2000** [overture-stack/arranger#503]
This will allow for significantly reducing the volume of data transported over the wire where UI is currently doing bucket counts with no interest in the actual bucket contents.

For kids first, will need an update on UI to use this new field instead of pulling all buckets where applicable

- counts on server side, rather than individual bucket aggregations 
-  cant use cardinality aggregation; use .length to count and return.

**Comment by andricDu** [comment]
Work completed in arranger, will create new issue for integration with ARGO platform.
