### ISSUE TITLE
Upgrade Arranger to ES 7

### ISSUE THREAD

**Issue by rosibaj** [overture-stack/arranger#518]
https://www.elastic.co/guide/en/elasticsearch/reference/current/removal-of-types.html

Elasticsearch is removing mapping types. Arranger is current built to reply on ES 6.X and less, which relies on mapping types. We need to support ES v7 and greater. 

To support the upgrade of Arranger's support of ES, we need to: 
- [ ] Find all the places referring to type, and remove them.  These are not centralized, so there are many spots to look through.

**Comment by hlminh2000** [comment]
version `2.0.5` was released with tests against Elasticsearch `7.5.0`.
Release pipeline: https://jenkins.qa.cancercollaboratory.org/blue/organizations/jenkins/Overture.bio%2Farranger/detail/master/9/pipeline/44

Npm packages: https://www.npmjs.com/org/arranger
