### ISSUE TITLE
server-side hidden negative sqon

### ISSUE THREAD

**Issue by hlminh2000** [overture-stack/arranger#601]
This is needed for ICGC-ARGO's feature as designed here: https://wiki.oicr.on.ca/display/icgcargotech/File+Metadata+Access+Control

Basically it allows for consumer apps to define dynamic extensions to the filters passed by the front-end, which enables implementation of access control for underlying Elasticsearch data

## Detailed Description
Target usage:
```ts
      const { schema: argoArrangerSchema } = (await createProjectSchema({
        getNegativeFilter: () => {
            return {
              op: "and",
              content: [],
            };
      })) as { schema: GraphQLSchema };
```
The sqon returned by `getNegativeFilter` should be applied as:
```
{
  op: "and",
  content: [
    frontEndSqon,
    {
      op: "not",
      content: [
        getNegativeFilter()
      ]
    }
  ]
}
```
The `not` operation is used to prevent injection attacks. With a whitelist approach, client-side may pass sqons that extend the whitelist, resulting in leakage. We are implementing this logic directly in Arranger to prevent implementation mistakes for consuming apps.

## Possible Implementation
pass the `getNegativeFilter` function all the way down to `modules/mapping-utils/src/resolveAggregations.js` and `modules/mapping-utils/src/resolveHits.js` from `modules/server/src/startProject.js`.

**Comment by rosibaj** [comment]
@hlminh2000 i think i cannot test this one any way... is this version of arranger tagged and brought into argo?

**Comment by hlminh2000** [comment]
> @hlminh2000 i think i cannot test this one any way... is this version of arranger tagged and brought into argo?

yes! I've brought it in :) if portal is still working, it's good ;)

**Comment by rosibaj** [comment]
excellent! all looks well then!
