### ISSUE TITLE
Feature Request: Date Range input facet 

### ISSUE THREAD

**Issue by rosibaj** [overture-stack/arranger#668]
![image](https://user-images.githubusercontent.com/15824252/112680787-2edba900-8e44-11eb-975b-4d2077d6621f.png)

- user can type the date in this format
- user can click the calendar icon an select a date from teh calendar

You can use a calendar library that works for you and Kim can review any UI that's implemented for it

**Comment by christinayung** [comment]
Looks like it is possible to have do dates out of the box.  Its positioning is just a little off at the moment.
![image.png](https://images.zenhubusercontent.com/5bbe9c22307bc60241e3aa93/44cfd7b9-4ae1-4be7-88fc-9746e219fda4)

**Comment by caravinci** [comment]
indeed! they just need a bit of styling, like I mentioned yesterday at standup. 🙌🏻
And they seem to work well too, if I'm not mistaken (unlike the number range component).

**Comment by rosibaj** [comment]
@caravinci i looked at this in dev environment and am still experiencing some styling issues: 
![image](https://user-images.githubusercontent.com/15824252/117184462-c79c0780-ada6-11eb-8e94-419399872b42.png)

**Comment by caravinci** [comment]
The calendar relocates itself under the field if you scroll the facets panel down a bit; but I'm not quite sure why it's opening above in your browser, as it obviously doesn't have enough space above it. Will do some research on it to see if I can figure out a quick solution.
