### ISSUE TITLE
CSS Autoprefixer

### ISSUE THREAD

**Issue by hlminh2000** [overture-stack/arranger#69]
We should have an autoprefixer so you can leave the prefixes off in any css module.

**Comment by Jephuff** [comment]
CSS modules (css files that are loaded with `import`) should already have this, so this issue would apply to updating the theme static files to have an auto prefixer (or importing them as modules)

**Comment by caravinci** [comment]
This functionality comes out of the box with the latest changes in the Theme Context.
As the CSS files are gradually being eliminated, this ticket can be closed now.
