### ISSUE TITLE
Review Arranger 3.0 Approach

### ISSUE THREAD

**Issue by b-f-chan** [overture-stack/arranger#703]
Task for @caravinci to review proposed Arranger 3.0 approach before we do a more detailed task breakdown and start development:

https://wiki.oicr.on.ca/display/OV/Arranger+3.0+Planning

Take this time to review the strategy and do own investigation/analysis of codebase to make sure it aligns with proposal.

Comments/questions can be added to the Wiki page, but feel free to add any tangential notes in this ticket.

**Comment by caravinci** [comment]
Tasks:
1. ~Review document, give preliminary assessment of work for stage 1 (restructuring modules while keeping feature parity).~
2. Study internal structure of the `server` modules, in order to implement new features, etc.
3. Amend this comment

**Comment by caravinci** [comment]
After further study of arranger (I wasn't very well aware of how it fits in an app until now), the right approach is to first set up a mock portal, in which changes to the services are testable live while work is being done.

For ease of future development, I may consider implementing such a tool as part of the testing/showcasing/documentation of Arranger 3.0 (to go along with storybook, etc.)
