### ISSUE TITLE
Restructure Arranger Codebase

### ISSUE THREAD

**Issue by b-f-chan** [overture-stack/arranger#704]
The existing arranger codebase must be restructured and simplified from 7 modules into 3 before any new features are developed or existing features re-written/optimized.

This prerequisite step will make the modules easier to work with for both planned and future feature development.

This involves:

- Resolving dependencies between the existing modules so we can achieve the new modules
- Updating the GitHub folder organization to reflect the new modules
- Updating Lerna so the new modules are packaged properly
- Testing the restructured code as-is in an existing project to make sure it works

**Comment by headsoup** [comment]
The codebase has been restructured as planned, and tested extensively in VirusSeq, both in standalone and as an API dependency.
This Epic can be closed.
