### ISSUE TITLE
Resolve Server Dependencies: `mapping-utils`

### ISSUE THREAD

**Issue by b-f-chan** [overture-stack/arranger#705]
Resolve dependencies on the `mapping-utils` library by moving it into the existing `server` module.

Since there are 3 libraries moving into `server`, we will treat these as separate tasks, migrating each one and testing them locally before moving onto the next one.

**Comment by caravinci** [comment]
Dependencies:
- Components imports
  - `columnsToGraphql` function, used only by `components` and `mapping-utils` itself
  - `esToAggTypeMap` dictionary object, used only by `components` and `mapping-utils` itself
  - `mappingToDisplayTreeData` object with a function and a mock object (used only for stories)
      ^^^^^^^^^^^^^^^^^^^^ not needed in server or admin, so can be safely removed from `mapping-utils`

**Comment by b-f-chan** [comment]
Tested successfully in #711.  Closing.
