### ISSUE TITLE
Resolve Server Dependencies: `middleware`

### ISSUE THREAD

**Issue by b-f-chan** [overture-stack/arranger#706]
Resolve dependencies on the `middleware` library by moving it into the existing `server` module.

Since there are 3 libraries moving into `server`, we will treat these as separate tasks, migrating each one and testing them locally before moving onto the next one.

**Comment by caravinci** [comment]
Disbanding this one first, as it doesn't depend on any other Arranger module.
The resulting duplicated code will likely be de-duplicated once the other modules are merged amongst themselves.

**Comment by caravinci** [comment]
Dependencies:
- Server imports 
  - `CONSTANTS` file with several different exports
  - `buildQuery` function
  - `esToSafeJsInt` function
- Schema imports 
  - `CONSTANTS` file with several different exports
- mapping-utils imports 
  - `CONSTANTS` file with several different exports
  - `buildAggregations` function
  - `flattenAggregations` function

**Comment by b-f-chan** [comment]
Tested successfully in #711.  Closing.
