### ISSUE TITLE
Update Lerna Publication Package

### ISSUE THREAD

**Issue by b-f-chan** [overture-stack/arranger#710]
After all Arranger modules are restructured, Lerna needs to be updated so that the new modules can be properly packaged and published (since we are reducing from 7 to 3).

Tasks:

- Update Lerna settings/config to grab code from the 3 new sources and publish the packages
- Also update Lerna settings/config to only publish packages with actual changes; today we have it configured such that Lerna will republish **everything** even if only one module changed

**QUESTION:** Since this is not production ready, how do we publish a temporary version of the packages just for our own testing?

**Comment by caravinci** [comment]
**TL;DR: this is not an urgent task yet.**

---
Along with the module consolidation, Lerna is set up to not hoist the packages/dependencies anymore, as the three resulting modules do not depend on each other directly.
This works well enough for refactoring and implementation purposes, as we're not releasing new public versions just yet; however, it is unclear to me at this time what changes may or not be necessary for actual releases later on.

Therefor, I'm moving this ticket back to ready for implementation until we're ready to make the new version publicly available.

**Comment by caravinci** [comment]
Update: As part of this ticket, I'm evaluating alternatives to Lerna.

Context: Doing some work in Arranger's publication process, triggered by changes in the way NPM handles its authentication, I've had a chance to study the internals of how Lerna publishes packages.

The work consisted of switching the existing `username` + `password` combo for the automation account, which triggered a confirmation email being sent; defeating the CI ideals.
I was able to restore publication automation using what NPM calls an 'automation token', although Lerna isn't *fully* compatible with those (yet?).

Furthermore, Lerna seems to not have received any functional bugfixes (mostly vulnerabilities were updated last year). As part of this ticket I'm evaluating alternatives for our monorepo management, in case the tool has abandoned by its creators, and to ensure we can enforce the right safety measures, such as requiring 2FA for maintainers, etc.

**Comment by b-f-chan** [comment]
Still in progress

**Comment by caravinci** [comment]
Updated Lerna to v4.0, and tested it by publishing two beta versions (updating vulnerable dependencies). 

Will run some extra tests for the automation token extra security measures later (not through this ticket), but all systems work OK.

Closing this, as it is only dev testable.
