### ISSUE TITLE
Design & Implement Data Fetch Interface

### ISSUE THREAD

**Issue by b-f-chan** [overture-stack/arranger#730]
Before separating the presentation and data layer in the UI components, we need to spec out details of the interface to fetch the data provided by the Arranger server, and then implement it

**Outcome:** An implemented, testable interface that is self-documenting (TypeScript)

**Comment by caravinci** [comment]
Connecting #323, as it seems related/relevant.

**Comment by caravinci** [comment]
Opened PR with the following changes:

- Ports the old data fetching function from the <Arranger /> root component into the new context provider, and allows for local customisation of fetcher per context invocation (this closes @323).
- Improves the TypeScript implementation, adding type definitions to the published package, and enabling the use of absolute paths (to avoid ../ hell).
- Includes collateral improvements for some existing helper functions.
- unrelated: updates the Elasticsearch docker image version in the docker-compose file.
