### ISSUE TITLE
Create Context Provider in React

### ISSUE THREAD

**Issue by b-f-chan** [overture-stack/arranger#731]
First step to create data fetching layer and context provider

**Comment by b-f-chan** [comment]
As a result of this ticket, a running feature branch was opened.  That branch will remain open, however, this ticket can be closed once the context provider has been implemented.

**Comment by caravinci** [comment]
The data context provider has been fully implemented and works as intended.
Documentation about its functionality and usage is pending, to be created along with that for the rest of the changes.
