### ISSUE TITLE
Align Facet elements to the first line

### ISSUE THREAD

**Issue by headsoup** [overture-stack/arranger#783]
As seen in the following screen capture, the facets are currently aligned to the vertical center of a facet (e.g. red line), which makes inconsistent whenever a facet's value extends into multiple lines.

The elements should all align atop the facet (e.g. green line.)

![image.png](https://images.zenhubusercontent.com/5defce3f99bcf0b1b8a98d24/36cedb56-8524-4101-96e4-753e00729731)

**Comment by caravinci** [comment]
Fixed in `beta.11`

![image.png](https://images.zenhubusercontent.com/5defce3f99bcf0b1b8a98d24/3cf91aca-1727-4aee-b70e-b62210568eb7)
