### ISSUE TITLE
make seed-es error

### ISSUE THREAD

**Issue by MitchellShiell** [overture-stack/arranger#849]
when running make `make seed-es` you get the following 

```
****************  Initializing file_centric index 
The directory /Users/chiara/arranger/elasticsearch does not exist
make: *** [seed-es] Error 1
```

error stems from this commit: https://github.com/overture-stack/arranger/commit/4995cec3e66ee1a09ed86df1174a31f6158fc2c7

Removing and reverting the changes in the make file on lines 25 and 132 allows make seed-es to run

**Comment by justincorrigible** [comment]
Nice catch, @MitchellShiell!
As it turns out, the issue was caused by my merging some changes by mistake, which I had made for some custom project I was working on

This should now be solved and improved in develop.
Thanks for bringing it to my attention 🙏
