### ISSUE TITLE
Replace `node-sass` with `sass`

### ISSUE THREAD

**Issue by ciaranschutte** [overture-stack/arranger#894]
https://www.npmjs.com/package/node-sass

`node-sass` is deprecated and causes headaches from it's executable while running `npm i` with latest node LTS versions
 
we should upgrade to `sass` as is officially recommended

**Comment by MitchellShiell** [comment]
Issue identified: Python version dependency for node-gyp, as described here: https://github.com/nodejs/node-gyp?tab=readme-ov-file#installation

`Python >= v3.12 requires node-gyp >= v10` while Arranger uses node-gyp v8.

workaround: downgrade Python

actual solution: update node-gyp.
