### ISSUE TITLE
Deployment model for arranger service(s) (docker)

### ISSUE THREAD

**Issue by andricDu** [overture-stack/arranger#98]
Figure it out and do it.

**Comment by andricDu** [comment]
@jonathanganesh We will need to setup a docker hub build for the server api for arranger.

**Comment by jonathanganesh** [comment]
Great, I will check with Jeff.

**Comment by andricDu** [comment]
Netlify will be leveraged and @jonathanganesh and @alex-wilmer have started  to work together regarding allowing for API updated to be triggered through a user action in the UI.
